#pragma once

#define SEPARATOR '_'

#define ACKNOWLEDGE "OK"


enum { CREATION, TOKEN_CHOICE, NOTHING};


enum { STREET, STATION, CHANCE, COMMUNITY_CHEST, JAIL, COMPANY, TAX, GO_CASE, GO_TO_JAIL, FREE_PARKING};


enum { ACKNOWLEDGE_REQUIERED, ACKNOWLEDGE_NOT_REQUIERED};

enum { OFFSET, OFFSET_ACTION};
