
@SET NUMBER_OF_SMT3_USED=15
@SET NUMBER_OF_FIRST_SMT3_PORT=8080
@SET NUMBER_OF_MISSION_ELEMENTAIRE_A_TRAITER_PAR_SMT3=500

@SET PORT_SMT3=%NUMBER_OF_FIRST_SMT3_PORT%

@SET NUMERO_SMT3_COURANT=0

:LOOP_DEMARRER_SIMULATION

@set /A NUMERO_SMT3_COURANT=NUMERO_SMT3_COURANT+1

@ECHO %DATE% %TIME% Launch SMT3 number %NUMERO_SMT3_COURANT% / %NUMBER_OF_SMT3_USED%

@ECHO %DATE% %TIME% NUMERO_PREMIERE_MISSION_ELEMENTAIRE_SMT3_COURANT : %NUMERO_PREMIERE_MISSION_ELEMENTAIRE_SMT3_COURANT%

@SET /A NUMERO_DERNIERE_MISSION_ELEMENTAIRE_SMT3_COURANT=NUMERO_DERNIERE_MISSION_ELEMENTAIRE_SMT3_COURANT+NUMBER_OF_MISSION_ELEMENTAIRE_A_TRAITER_PAR_SMT3
@ECHO %DATE% %TIME% NUMERO_DERNIERE_MISSION_ELEMENTAIRE_SMT3_COURANT : %NUMERO_DERNIERE_MISSION_ELEMENTAIRE_SMT3_COURANT%

@set /A PORT_SMT3=PORT_SMT3+1
@ECHO %DATE% %TIME% PORT_SMT3 : %PORT_SMT3%

@ECHO %DATE% %TIME% call C:\Users\Yann\AppData\Local\Programs\Python\Python39\python.exe ProduireSimplesRunsAndExporterSimplesRunsSimulations.py  --numero_premiere_mission_elementaire_a_traiter=1    --numero_derniere_mission_elementaire_a_traiter=999 --port_smt3=8080
@timeout /t 10

IF %NUMERO_SMT3_COURANT%==%NUMBER_OF_SMT3_USED% GOTO :LAST_SIMULATION_LAUNCHED
GOTO :INCREMENTER_VARIABLES_POUR_PROCHAIN_SMT3


:INCREMENTER_VARIABLES_POUR_PROCHAIN_SMT3

@SET /A NUMERO_PREMIERE_MISSION_ELEMENTAIRE_SMT3_COURANT=NUMERO_PREMIERE_MISSION_ELEMENTAIRE_SMT3_COURANT+NUMBER_OF_MISSION_ELEMENTAIRE_A_TRAITER_PAR_SMT3
@ECHO %DATE% %TIME% Prochain NUMERO_PREMIERE_MISSION_ELEMENTAIRE_SMT3_COURANT : %NUMERO_PREMIERE_MISSION_ELEMENTAIRE_SMT3_COURANT%


@set /A PORT_SMT3=PORT_SMT3+1
@ECHO %DATE% %TIME% Prochain PORT_SMT3 : %PORT_SMT3%


:LAST_SIMULATION_LAUNCHED

@ECHO %DATE% %TIME%  All simulations  launched, will exit

@timeout /t 100

exit
