
global SMT_mE_aig

   % Complément avec les données du 2e ordre sur les aiguilles
   SMT_mE_aig = struct( ...
				  'cdv_commut_created_empty',{...
			   [],[],[]},...
				  'cdv_commut_created_full',{...
								171,...
								171,...
								171...
							}...
						);
						